FROM node:20-alpine AS builder
WORKDIR /app
COPY hra-frontend/package.json .
RUN npm install --legacy-peer-deps
COPY hra-frontend/ .
RUN npm run build

FROM nginx:alpine
RUN apk add --no-cache gettext
COPY --from=builder /app/dist /usr/share/nginx/html
COPY hra-frontend/nginx.conf.template /etc/nginx/conf.d/nginx.conf.template
COPY hra-frontend/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh && chmod +x /entrypoint.sh
EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
