# Generated by Django 5.0.6 on 2026-03-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("da", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("ta", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pf_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "loss_of_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("working_days", models.IntegerField(default=0)),
                ("present_days", models.IntegerField(default=0)),
                ("absent_days", models.IntegerField(default=0)),
                ("leaves_taken", models.IntegerField(default=0)),
                ("pdf_path", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payslips_payslip",
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "month", "year")},
            },
        ),
    ]
