# Generated by Django 5.0.6 on 2026-03-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_leaves_total", models.IntegerField(default=20)),
                ("paid_leaves_used", models.IntegerField(default=0)),
                ("unpaid_leaves_total", models.IntegerField(default=10)),
                ("unpaid_leaves_used", models.IntegerField(default=0)),
                ("sick_leaves_total", models.IntegerField(default=10)),
                ("sick_leaves_used", models.IntegerField(default=0)),
                ("casual_leaves_total", models.IntegerField(default=8)),
                ("casual_leaves_used", models.IntegerField(default=0)),
                ("year", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employees_leave_balance",
                "ordering": ["-year"],
                "unique_together": {("user", "year")},
            },
        ),
    ]
